### ISSUE TITLE
Search returns no results

### ISSUE THREAD

**Issue by nosoop4u** [maforget/ComicRack_AmazonScrapper#5] opened 2024-06-10 17:17 UTC
Tried with about 10 different comic issues that are all found when searching Amazon Kindle Store directly, even the simplest comic names, e.g., "Carnage #8."  Search by just series name returns nothing also.  There are no error messages, and it does appear to do something (the busy cursor appears for 2-10s depending on the complexity of the search).

Restarted ComicRack, restarted computer, no change.

- CR version 0.9.178 64-bit
- Scraper version 1.0
- Windows 10 Pro 22H2 19045.4412

**Comment by maforget** [comment] 2024-06-11 12:55
Don't use v1. Update to the latest nightly. Already fixed. 

Duplicate of #4.

**Closed as not planned** 2024-06-11 12:55 UTC
